language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pyflakes pep8 coverage
# command to run tests
script:
  - pep8 softhyphen
  - pyflakes softhyphen