 version: '2'
 services:
   db:
     image: postgres
   web:
     build: .
     command: pip install -r requirements.txt
     command: python manage.py runserver 0.0.0.0:8000
 #    command: echo "from django.contrib.auth.models import User; User.objects.filter(email='admin@example.com').delete(); User.objects.create_superuser('admin@example.com', 'admin', 'admin')" | python manage.py shell
     volumes:
       - .:/app
     ports:
       - "8000:8000"
     depends_on:
       - db