 version: '2'
 services:
   db:
     image: postgres
     volumes:
       - /datap/pgsql:/var/lib/postgresql/data
   web:
     build: .
     command: pip install -r requirements.txt
     command: python manage.py runserver 0.0.0.0:8000
 #    command: echo "from django.contrib.auth.models import User; User.objects.filter(email='admin@example.com').delete(); User.objects.create_superuser('admin@example.com', 'admin', 'admin')" | python manage.py shell
     volumes:
       - .:/app
     ports:
       - "8000:8000"
       - "8888:8888"
     depends_on:
       - db
   pgadmin:
     image: fenglc/pgadmin4
     hostname: pgadmin
     volumes:
       - /datap/.pgadmin:/root/.pgadmin:rw
     links:
       - db
     ports:
       - "5050:5050"