# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
