# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20170213_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='people',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
