# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_date',
            new_name='created_datetime',
        ),
        migrations.AddField(
            model_name='task',
            name='closed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
